/* Lexique de Java Rookie : un terme, une définition courte, la leçon où il apparaît pour la première fois. */
JR.lexique([
  /* ---------- m01 : premiers pas ---------- */
  { terme: "programme", def: "Une suite d'ordres que l'ordinateur exécute, l'un après l'autre.", lecon: "m01-l01" },
  { terme: "cadre", def: "Le texte obligatoire autour de ton code : <code>public class Main { public static void main(String[] args) { … } }</code>. On le recopie tel quel ; chaque mot est expliqué au fil du parcours.", lecon: "m01-l01" },
  { terme: "JDK", def: "Le kit de développement Java : il contient <code>javac</code> (pour compiler) et <code>java</code> (pour exécuter). À installer pour programmer sur ton ordinateur.", lecon: "m01-l01" },
  { terme: "STDIN", def: "L'entrée standard : ce que le programme lit au clavier. Dans un outil en ligne, c'est la zone où l'on tape à l'avance les valeurs à lire.", lecon: "m01-l01" },
  { terme: "compilateur (javac)", def: "Le traducteur : il vérifie ton fichier <code>.java</code> et le traduit en <strong>bytecode</strong>, un code compact rangé dans un fichier <code>.class</code> et destiné à la JVM. S'il trouve une faute, il refuse et affiche un message.", lecon: "m01-l02" },
  { terme: "JVM (machine virtuelle Java)", def: "Le programme qui exécute le bytecode (commande <code>java</code>). Il existe une JVM pour Windows, Linux et Mac : le même <code>.class</code> tourne partout.", lecon: "m01-l02" },
  { terme: "classe", def: "Au début, la boîte qui contient ton code ; une classe <code>public</code> porte le nom de son fichier. Plus tard, le plan qui décrit des objets semblables : leurs attributs et leurs opérations. Image : le plan d'architecte.", lecon: "m01-l02" },
  { terme: "main (méthode principale)", def: "Le point de départ du programme : Java commence l'exécution à la première ligne de <code>main</code>.", lecon: "m01-l02" },
  { terme: "bloc", def: "Un groupe de lignes entre <code>{</code> et <code>}</code>. Chaque <code>{</code> ouverte doit être fermée.", lecon: "m01-l02" },
  { terme: "instruction", def: "Un ordre donné à l'ordinateur, terminé par <code>;</code>.", lecon: "m01-l02" },
  { terme: "casse", def: "La différence entre majuscules et minuscules. Java la respecte : <code>System</code> et <code>system</code> sont deux mots différents.", lecon: "m01-l02" },
  { terme: "commentaire", def: "Une note pour les humains, ignorée par Java. Elle commence par <code>//</code> et va jusqu'à la fin de la ligne.", lecon: "m01-l02" },
  { terme: "erreur de compilation", def: "Une faute détectée par <code>javac</code> avant l'exécution : rien ne s'exécute. Le message donne le fichier, la ligne et la cause.", lecon: "m01-l03" },

  /* ---------- m02 : variables et types ---------- */
  { terme: "variable", def: "Une case de la mémoire qui porte un nom et contient une valeur. Image : une boîte étiquetée.", lecon: "m02-l01" },
  { terme: "type", def: "La sorte de valeur qu'une variable accepte : <code>int</code> pour un entier, <code>double</code> pour un réel, <code>String</code> pour un texte…", lecon: "m02-l01" },
  { terme: "déclaration / initialisation", def: "Déclarer, c'est créer une variable avec son type et son nom (<code>int age;</code>). Initialiser, c'est lui donner sa première valeur. <code>int age = 20;</code> fait les deux d'un coup.", lecon: "m02-l01" },
  { terme: "mot réservé", def: "Un mot que Java utilise déjà (<code>int</code>, <code>class</code>, <code>if</code>…) et qu'on ne peut pas prendre comme nom de variable.", lecon: "m02-l01" },
  { terme: "affectation", def: "<code>nom = valeur;</code> : on calcule à droite, puis on range le résultat dans la variable de gauche. L'ancienne valeur est perdue. Se lit « reçoit ».", lecon: "m02-l02" },
  { terme: "concaténation", def: "Le <code>+</code> entre un texte et une autre valeur : il colle les morceaux bout à bout (<code>\"a \" + 21</code> donne <code>\"a 21\"</code>). Image : des wagons accrochés.", lecon: "m02-l02" },
  { terme: "String", def: "Le type des textes, écrits entre guillemets doubles <code>\" \"</code>. Il prend une majuscule et n'est pas un type primitif.", lecon: "m02-l02" },
  { terme: "type primitif", def: "Un des 8 types de base de Java : <code>byte</code>, <code>short</code>, <code>int</code>, <code>long</code>, <code>float</code>, <code>double</code>, <code>char</code>, <code>boolean</code>.", lecon: "m02-l03" },
  { terme: "int / long", def: "Les nombres entiers. <code>int</code> va jusqu'à environ 2 milliards ; <code>long</code>, beaucoup plus loin (valeur suivie de <code>L</code> : <code>8000000000L</code>).", lecon: "m02-l03" },
  { terme: "double / float", def: "Les nombres réels, écrits avec un point (<code>12.5</code>). <code>double</code> est le choix par défaut ; <code>float</code> est moins précis et demande un <code>f</code> (<code>3.14f</code>).", lecon: "m02-l03" },
  { terme: "char", def: "Un seul caractère, entre apostrophes : <code>'A'</code>. À ne pas confondre avec <code>\"A\"</code>, qui est un texte.", lecon: "m02-l03" },
  { terme: "boolean", def: "Une valeur vraie ou fausse : <code>true</code> ou <code>false</code>, le VRAI / FAUX de l'algo.", lecon: "m02-l03" },
  { terme: "conversion implicite", def: "Java change tout seul le type d'une valeur vers un type « plus grand » : <code>byte → short → int → long → float → double</code>, et <code>char → int</code>. Pas de perte entre entiers ; vers <code>float</code> (ou de <code>long</code> vers <code>double</code>), un très grand nombre peut perdre ses derniers chiffres.", lecon: "m02-l04" },
  { terme: "cast (transtypage)", def: "<code>(type) valeur</code> : force la conversion vers un type plus petit, par exemple <code>(int) 2.9</code>. Image : le massicot qui coupe pour faire rentrer.", lecon: "m02-l04" },
  { terme: "troncature", def: "Ce que fait un cast vers <code>int</code> : il coupe la partie après la virgule, sans arrondir. <code>(int) 2.9</code> vaut 2, <code>(int) -2.7</code> vaut -2.", lecon: "m02-l04" },

  /* ---------- m03 : calculer et dialoguer ---------- */
  { terme: "division entière", def: "Entre deux entiers, <code>/</code> donne un entier : <code>7 / 2</code> vaut 3. Dès qu'un des deux est un réel, la division garde la partie décimale (<code>7.0 / 2</code> vaut 3.5).", lecon: "m03-l01" },
  { terme: "modulo (%)", def: "Le reste de la division entière : <code>7 % 3</code> vaut 1. Ce n'est pas un pourcentage.", lecon: "m03-l01" },
  { terme: "priorité des opérateurs", def: "L'ordre de calcul : <code>*</code>, <code>/</code> et <code>%</code> passent avant <code>+</code> et <code>-</code>, puis on va de gauche à droite. Les parenthèses passent avant tout.", lecon: "m03-l01" },
  { terme: "incrémentation (++ et --)", def: "<code>i++</code> ajoute 1 à <code>i</code>, <code>i--</code> retire 1. En post-incrémentation (<code>i++</code>), on utilise la valeur puis on augmente ; en pré-incrémentation (<code>++i</code>), on augmente puis on utilise.", lecon: "m03-l02" },
  { terme: "Scanner", def: "L'outil qui lit ce que l'utilisateur tape au clavier : <code>nextInt()</code>, <code>nextDouble()</code>, <code>next()</code> (un mot), <code>nextLine()</code> (toute la ligne).", lecon: "m03-l03" },
  { terme: "import", def: "Ligne placée en haut du fichier pour dire où trouver un outil qui n'est pas chargé d'office : <code>import java.util.Scanner;</code> Image : le rayon du magasin.", lecon: "m03-l03" },
  { terme: "invite", def: "Le message affiché juste avant une saisie, pour dire à l'utilisateur quoi taper : <code>System.out.print(\"Ton âge : \");</code>", lecon: "m03-l03" },
  { terme: "erreur d'exécution", def: "Le programme a compilé, mais il s'arrête en route (par exemple, un mot tapé là où un nombre était attendu).", lecon: "m03-l03" },

  /* ---------- m04 : choisir et répéter ---------- */
  { terme: "condition", def: "Un calcul ou une comparaison qui vaut <code>true</code> ou <code>false</code> (<code>moyenne >= 10</code>). Elle décide du chemin suivi.", lecon: "m04-l01" },
  { terme: "== (comparaison)", def: "Teste l'égalité de deux valeurs et donne <code>true</code> ou <code>false</code>. À ne pas confondre avec <code>=</code>, qui range une valeur.", lecon: "m04-l01" },
  { terme: "if / else", def: "Choisit un chemin : si la condition est vraie, le bloc du <code>if</code> ; sinon, celui du <code>else</code>. Image : un aiguillage de train.", lecon: "m04-l01" },
  { terme: "opérateurs logiques (&&, ||, !)", def: "Combinent des conditions : <code>&&</code> (ET, les deux vraies), <code>||</code> (OU, au moins une vraie), <code>!</code> (NON, inverse).", lecon: "m04-l02" },
  { terme: "switch", def: "Choisit parmi plusieurs valeurs précises (<code>case</code>). <code>break</code> termine le cas, <code>default</code> traite tous les autres. Sans <code>break</code>, on continue dans le cas suivant.", lecon: "m04-l03" },
  { terme: "boucle", def: "Un bloc répété plusieurs fois. Chaque passage s'appelle une itération. Image : une flèche qui revient au départ.", lecon: "m04-l04" },
  { terme: "for", def: "La boucle pour un nombre de tours connu : <code>for (int i = 1; i <= 5; i++) { … }</code> (départ ; condition ; pas).", lecon: "m04-l04" },
  { terme: "accumulateur", def: "Une variable qui cumule un résultat au fil des tours (une somme, un produit). Elle est initialisée avant la boucle.", lecon: "m04-l04" },
  { terme: "portée", def: "L'ensemble des instructions où une variable existe : de sa déclaration jusqu'à la <code>}</code> qui ferme son bloc.", lecon: "m04-l04" },
  { terme: "while / do…while", def: "Répètent tant qu'une condition est vraie. <code>while</code> teste avant (0 tour possible) ; <code>do…while</code> teste après (au moins 1 tour).", lecon: "m04-l05" },
  { terme: "boucle infinie", def: "Une boucle dont la condition reste toujours vraie : elle ne s'arrête jamais. Souvent, on a oublié de faire changer la variable testée.", lecon: "m04-l05" },

  /* ---------- m05 : méthodes ---------- */
  { terme: "méthode", def: "Un bloc de code nommé, qu'on exécute à la demande en l'appelant par son nom (le cours dit « fonction »). Image : une machine avec un bouton.", lecon: "m05-l01" },
  { terme: "void", def: "Indique qu'une méthode ne renvoie aucun résultat.", lecon: "m05-l01" },
  { terme: "static", def: "Une méthode <code>static</code> appartient à la classe : on l'appelle directement, sans créer d'objet avant.", lecon: "m05-l01" },
  { terme: "paramètre / argument", def: "Le paramètre est la variable déclarée dans la définition de la méthode ; l'argument est la valeur donnée à l'appel, qui vient remplir le paramètre.", lecon: "m05-l02" },
  { terme: "return", def: "Renvoie une valeur à celui qui a appelé la méthode, et sort de la méthode. Son type doit correspondre au type de retour. Renvoyer n'est pas afficher.", lecon: "m05-l02" },
  { terme: "variable locale", def: "Une variable déclarée dans une méthode (ou un bloc) : elle n'existe que pendant l'exécution de ce bloc, et doit recevoir une valeur avant d'être lue.", lecon: "m05-l02" },
  { terme: "signature", def: "Le nom d'une méthode et les types de ses paramètres : <code>plus(int, int)</code>. Le type de retour n'en fait pas partie.", lecon: "m05-l03" },
  { terme: "surcharge", def: "Plusieurs méthodes de même nom, avec des signatures différentes. Le compilateur choisit la bonne d'après les arguments de l'appel ; le type de retour ne compte pas.", lecon: "m05-l03" },

  /* ---------- m06 : objets ---------- */
  { terme: "objet", def: "La représentation d'une entité du monde réel ou virtuel : un état (les valeurs de ses attributs), un comportement (ses opérations) et une identité (ce qui le distingue d'un autre objet, même identique).", lecon: "m06-l01" },
  { terme: "attribut", def: "Une donnée qui décrit un objet (son nom, son âge…). En Java, une variable déclarée dans la classe, hors des méthodes.", lecon: "m06-l01" },
  { terme: "instance / instanciation", def: "Une instance est un objet fabriqué à partir d'une classe (Adama est une instance de la classe Etudiant) ; l'instanciation est cette fabrication. Image : la maison construite d'après le plan.", lecon: "m06-l01" },
  { terme: "UML", def: "Une notation graphique : une classe y est un rectangle à trois compartiments, nom / attributs / opérations.", lecon: "m06-l01" },
  { terme: "new et référence", def: "<code>new Etudiant()</code> fabrique un nouvel objet. La variable qui le reçoit contient une <strong>référence</strong> : un lien vers l'objet, pas l'objet lui-même. Image : une télécommande.", lecon: "m06-l02" },
  { terme: "méthode d'instance", def: "Une méthode écrite sans <code>static</code> : on l'appelle sur un objet (<code>e.afficher()</code>), et elle utilise les attributs de cet objet.", lecon: "m06-l02" },
  { terme: "constructeur", def: "Un bloc spécial, qui ressemble à une méthode, appelé par <code>new</code> pour remplir l'objet dès sa naissance. Il porte exactement le nom de la classe et n'a aucun type de retour, pas même <code>void</code>.", lecon: "m06-l03" },
  { terme: "constructeur par défaut", def: "Le constructeur sans paramètre que Java fournit tant que tu n'en écris aucun. Il disparaît dès que tu en écris un.", lecon: "m06-l03" },
  { terme: "this", def: "Dans une classe, désigne l'objet en cours : celui qu'on construit, ou celui sur lequel la méthode est appelée. <code>this.nom = nom;</code> range le paramètre <code>nom</code> dans l'attribut <code>nom</code>.", lecon: "m06-l03" },
  { terme: "null", def: "« Aucun objet » : la valeur d'une référence qui ne désigne rien, par exemple un attribut <code>String</code> jamais rempli. La télécommande ne pilote rien.", lecon: "m06-l03" },
  { terme: "encapsulation", def: "Cacher les détails internes d'un objet et n'offrir que des services. Les attributs sont <code>private</code> ; on les lit avec un accesseur (<code>getAge()</code>) et on les modifie avec un mutateur (<code>setAge(…)</code>), qui peut refuser une valeur incorrecte. Image : un distributeur de billets.", lecon: "m06-l04" },
  { terme: "public / private / protected", def: "Les visibilités : <code>public</code> (+) partout, <code>private</code> (−) seulement dans la classe, <code>protected</code> (#) dans le paquetage et les classes filles. Sans mot-clé : le paquetage seulement.", lecon: "m06-l04" },
  { terme: "paquetage", def: "Un groupe de classes rangées ensemble, comme un dossier.", lecon: "m06-l04" },
  { terme: "héritage (extends)", def: "Une classe fille reprend les attributs et méthodes de sa classe mère (pas ses constructeurs ; les membres <code>private</code> ne lui sont pas accessibles) et y ajoute ses particularités : <code>class Etudiant extends Personne</code> (« un étudiant est une personne »). Une seule mère en Java.", lecon: "m06-l05" },
  { terme: "super", def: "<code>super(…)</code> appelle le constructeur de la classe mère. Écris-le en première ligne du constructeur de la fille.", lecon: "m06-l05" },
  { terme: "exception", def: "Un objet qui décrit un problème survenu pendant l'exécution. <code>try { … } catch (…) { … }</code> la rattrape au lieu de laisser le programme s'arrêter. Image : le filet sous le trapéziste.", lecon: "m06-l06" },
  { terme: "interface", def: "Un contrat : une liste de méthodes promises. Une classe le signe avec <code>implements</code> et doit fournir ces méthodes, en <code>public</code>.", lecon: "m06-l06" },
  { terme: "tableau", def: "Une suite de cases numérotées, du même type (par exemple 30 notes). Simple mention ici : c'est la suite naturelle du parcours.", lecon: "m06-l06" },

  /* ---------- Messages d'erreur fréquents ---------- */
  { terme: "error: ';' expected", def: "Traduction : « point-virgule attendu ». Une instruction n'est pas terminée par <code>;</code>. Le chapeau <code>^</code> pointe là où il manque : juste après la fin de l'instruction.", lecon: "m01-l03" },
  { terme: "error: unclosed string literal", def: "Traduction : « texte non fermé ». Un guillemet ouvre un texte, mais aucun ne le ferme.", lecon: "m01-l03" },
  { terme: "error: package system does not exist", def: "Traduction : « le paquetage system n'existe pas ». Ne connaissant pas <code>system</code>, Java devine un nom de paquetage. En réalité, c'est une faute de casse : il faut <code>System</code>, avec une majuscule.", lecon: "m01-l03" },
  { terme: "error: class X is public, should be declared in a file named X.java", def: "Traduction : « la classe X est publique, elle devrait être dans un fichier nommé X.java ». Le nom du fichier doit être celui de la classe <code>public</code>, majuscules comprises. Sur OneCompiler, garde le nom <code>Main</code>.", lecon: "m01-l02" },
  { terme: "error: incompatible types: String cannot be converted to int", def: "Traduction : « types incompatibles : un String ne peut pas être converti en int ». On range un texte (entre guillemets) dans une variable numérique : <code>int age = \"20\";</code> Même cause pour <code>String cannot be converted to char</code> : <code>\"A\"</code> au lieu de <code>'A'</code>.", lecon: "m02-l01" },
  { terme: "error: variable x might not have been initialized", def: "Traduction : « la variable x n'a peut-être pas été initialisée ». On lit une variable locale avant de lui avoir donné une valeur.", lecon: "m02-l02" },
  { terme: "error: incompatible types: possible lossy conversion from double to int", def: "Traduction : « conversion avec perte possible de double vers int ». On range une valeur d'un type plus grand dans un plus petit : il faut un cast, <code>(int)</code>.", lecon: "m02-l04" },
  { terme: "error: cannot find symbol", def: "Traduction : « symbole introuvable ». Java ne connaît pas ce nom : faute de frappe, variable utilisée hors de sa portée, ou <code>import</code> oublié (par exemple pour <code>Scanner</code>).", lecon: "m03-l03" },
  { terme: "InputMismatchException", def: "Erreur d'exécution. Traduction : « la saisie ne correspond pas au type attendu ». Le Scanner attendait un nombre et a lu autre chose : un mot, ou un séparateur décimal qui ne correspond pas à la langue de la machine (virgule en français, point en anglais).", lecon: "m03-l03" },
  { terme: "error: incompatible types: int cannot be converted to boolean", def: "Traduction : « un int ne peut pas être converti en boolean ». Souvent <code>if (x = 5)</code> au lieu de <code>if (x == 5)</code>.", lecon: "m04-l01" },
  { terme: "error: bad operand types for binary operator '<='", def: "Traduction : « mauvais types pour l'opérateur <= ». Souvent <code>0 <= note <= 20</code> : il faut deux comparaisons, <code>note >= 0 && note <= 20</code>.", lecon: "m04-l02" },
  { terme: "error: illegal start of expression", def: "Traduction : « début d'expression interdit ». Java trouve un mot là où il ne peut pas en commencer un. Souvent : une méthode écrite à l'intérieur de <code>main</code> au lieu d'à côté, ou une accolade manquante.", lecon: "m05-l01" },
  { terme: "error: incompatible types: void cannot be converted to int", def: "Traduction : « void ne peut pas être converti en int ». On essaie de ranger le résultat d'une méthode <code>void</code>, qui ne renvoie rien.", lecon: "m05-l02" },
  { terme: "error: missing return statement", def: "Traduction : « instruction return manquante ». Une méthode qui doit renvoyer une valeur a un chemin qui se termine sans <code>return</code>.", lecon: "m05-l02" },
  { terme: "error: method … is already defined in class …", def: "Traduction : « la méthode … est déjà définie dans la classe … ». Deux méthodes ont la même signature (même nom, mêmes types de paramètres) : changer seulement le type de retour ne suffit pas.", lecon: "m05-l03" },
  { terme: "error: constructor X in class X cannot be applied to given types", def: "Traduction : « le constructeur X ne peut pas être appliqué aux types donnés ». Les arguments de <code>new</code> (ou de <code>super(…)</code>) ne correspondent à aucun constructeur écrit. Souvent : <code>new Etudiant()</code> alors qu'il n'existe qu'un constructeur avec paramètres.", lecon: "m06-l03" },
  { terme: "error: x has private access in C", def: "Traduction : « x est privé dans la classe C ». On accède à un attribut <code>private</code> depuis une autre classe : passe par son accesseur ou son mutateur.", lecon: "m06-l04" },
  { terme: "ArithmeticException: / by zero", def: "Erreur d'exécution. Traduction : « erreur arithmétique : division par zéro ». Une division entière par 0 : le programme compile, puis s'arrête à cette ligne.", lecon: "m06-l06" }
]);
